default: &default
  adapter: oracle_enhanced
  encoding: utf8
  database: "FREEPDB1"
  username: "root2"
  password: "root"
  host: "localhost"
  port: 1521
  # privilege: 'SYSDBA'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
